# Generated by Django 4.2.3 on 2023-07-17 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ver1', '0002_sentimentanalysis'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SentimentAnalysis',
            new_name='SentimentAnalysist',
        ),
    ]
